### ISSUE TITLE
(stretch) Add table with timestamps and result

### ISSUE THREAD

**Issue by ancasimon** [ancasimon/bear-watcher#8]
## User Story
As a user, looking at a bear card I should see time stamps and statuses for each time a bear caught a fish or attempted to catch a fish

## AC
WHEN I look at a bear card,
THEN I should see a table with two columns,
AND one column should display the time stamp,
AND the other should display the result (Failure or Success).

## Dev Notes
In `bearData.js`:
* Write a function called `buildBearActivityTable` that:
1. Should take a parameter of `activities` (meaning a generic array).
1. Runs only if there is at least one activity in it; if it is blank, the it doesn't print it.
1. Should build a domString with a table. 
1. In the domString, define the header data. 
1. Then, use a for loop to loop over the array of activities provided in the parameter and display the timestamp and type of each activity. 
1. Close the table body and table tags outside the for loop. 
1. return the domString to reprint it. 
Now - let's define how/when this table gets built: 
* Update the `trackFailure` function so that:
1. It grabs the id of the element with a class of card that is closest to the button that is the target of the event when this function is called and puts it in a variable. You can console.log it here to confirm. (use `.closest` method)
1. Then, it identifies the bear's position in the array who has that id (via the findIndex method).  You can console log the bear with that position if you want. 
1. Then it defines the timestamp and type variables (left empty). 
1. Then it defines the object that uses those two variables as keys (`newActivity`) in our case. 
1. When you click the Tried It button, the function should create the `newActivity` object with 2 key-value pairs: `timestamp` for the date & time (us `Date.now()`) and `type` of Failure.
1. Create an empty array variable of activities.
1. Push any `newActivity` into the activities' array for that specific bear whose position we identified earlier. You can console log the array of activities to check. 
1. Now - call the function that builds the activity table inside the bear's card: `buildBearActivityTable`. 
1. And call the function that builds the whole river of bears again: `river.buildBearSleuth();`
* Do the same thing for the `trackSuccess` function - for the GotIt buttons and a type of Success (for the `newActivity`).

**Comment by ancasimon** [comment]
Bootstrap table:
```
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
</tbody>
</table>
```

**Comment by ancasimon** [comment]
QUESTION: What exactly do we need to copy from moment.js?

also: got this warning that I think has to do with the moment.js script link:
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 01/01/2020, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js:1:3368)
    at Ot (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js:1:21539)
    at Tt (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js:1:22250)
    at bt (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js:1:22332)
    at c (https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js:1:209)
    at Object.buildBearActivityTable (http://localhost:8080/javascripts/helpers/data/bearData.js:51:27)
    at Object.buildBearSleuth (http://localhost:8080/javascripts/components/river.js:16:39)
    at init (http://localhost:8080/javascripts/main.js:7:11)
    at http://localhost:8080/javascripts/main.js:10:1
